title: Ryans
author: Me
theme: minima
email: my-email
description: > This

# social links
twitter_username: your-twitter-handle 
github_username:  your-github-handle 

show_excerpts: true # set to false to remove excerpts on the homepage
